# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7fa92ff22d38b06905a7fc36332d13dce943b3e4d367a7ae4c89d022ac78ff98d527ccb3cb0bbfb7275cc359db4a1c451578121c4750e39f7479d5d74ef8ecbe

test:
  secret_key_base: 10d990795fb4e7fc9d4b908b568688d25b7621284f11beb2fecb5d7219beeb7233622a60b333f1273d8a49bc72e673ef56292fbba274bdfbf0f148a9241d10f0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
